# Site
name: "挖井"
title: "类库大魔王的挖井日记"
description: "挖一口属于自己的井"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
google_analytics: 'UA-52744860-1'
disqus: 'missdeer'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:year/:month/:title/

# Authors
authors:
  missdeer:
    name: missdeer
    display_name: 类库大魔王
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: me@minidump.info
    web: https://minidump.info
    twitter: https://twitter.com/missdeerme
    description: "C++、Go多年用户，擅长跨平台(Windows/macOS/iOS/Android)应用架构设计与开发."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 15
paginate_path: /page/:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
