name: Build Blog

on: 
  push:
    branches:
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: prepare toolchain
      run: |
        sudo apt-get update -qq;
        sudo apt-get install -qq p7zip-full;

    - uses: actions/checkout@v2
      with:
        ref: master
    
    - name: Set up Go 
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
      id: go

    - name: Set up Ruby 
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Setup bundler
      run: |      
        gem install bundler        
        bundle install
        
    - name: Setup plantuml-cmd tool
      run: |      
        rm -rf plantuml-cmd _plantuml _site 
        git clone --depth=1 https://github.com/missdeer/plantuml-cmd.git 
        cd plantuml-cmd 
        go build 
        sudo mv plantuml-cmd /usr/local/bin/plantuml-cmd
        cd ..
        rm -rf plantuml-cmd
        
    - name: Setup minify tool
      run: |      
        git clone --depth=1 https://github.com/tdewolff/minify.git
        cd minify/cmd/minify
        go build -ldflags "-s -w -X 'main.Version=$(git describe --tags)'" -trimpath
        sudo mv minify /usr/local/bin/minify
        cd ../../..
        rm -rf minify
                        
    - name: Build site
      run: |
        rm -rf _site blog.7z
        sed -i '/baseurl/d' _config.yml 
        sed -i 's|https://www.ismisv.com|https://blog.ismisv.com|g' _config.yml
        sed -i 's|site.config\[\x27baseurl\x27\] +||g' _plugins/ditaa.rb
        cat _config.yml
        bundle exec jekyll build --trace

    - name: Minify files
      run: |
        cd _site
        find . -name '*.html' -type f -print | while read file; do /usr/local/bin/minify -o $file $file; done
        find . -name '*.css' -type f -print | while read file; do /usr/local/bin/minify -o $file $file; done
        find . -name '*.js' -type f -print | while read file; do /usr/local/bin/minify -o $file $file; done
        cd ..

    - name: upload to server
      run: |
        cd _site
        find . -name '*.png' -type f -exec rm -f {} \;
        find . -name '*.jpg' -type f -exec rm -f {} \;
        7z a ../blog-root.7z *
        cd ..
        sudo sysctl -w net.core.rmem_max=2500000
        curl -X POST -H "Content-Type: multipart/form-data" -F "originalFile=@blog-root.7z" ${{ secrets.BLOG_SERVER }}
